### ISSUE TITLE
Counter funktioniert nicht richtig

### ISSUE THREAD

**Issue by Meeresgott** [DomTHK/DLO_Lab#10]
Irgendwas mit dem Counter stimmt nicht. Die Zeit pro epoche ist mindestens 30 Sekunden, es werden aber ns angezeigt

**Comment by StrikerCatSharky** [comment]
Timer funktioniert richtig, default_timer ist in Sekunden (bei mir brauche ich ~3s, da ich bei den Daten irgendein fehler hab).
Beim print sagst du  "/ 1E9", es muss aber wenn du es in ns umwandeln willst "/ 1E-9" sein.

**Comment by Meeresgott** [comment]
Oha! Bin bei ns davon ausgegangen, dass aus ns gezählt werden und nicht, dass er direkt umrechnet. Sekunden ist fine für mich. Mache dann einfach den divisor weg
